/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconAndriod: typeof import('~icons/icon/andriod')['default']
  const IconAndroid: typeof import('~icons/icon/android')['default']
  const IconApple: typeof import('~icons/icon/apple')['default']
  const IconArrow: typeof import('~icons/icon/arrow')['default']
  const IconDust: typeof import('~icons/icon/dust')['default']
  const IconError: typeof import('~icons/icon/error')['default']
  const IconHurricane: typeof import('~icons/icon/hurricane')['default']
  const IconLocation: typeof import('~icons/icon/location')['default']
  const IconSpinner: typeof import('~icons/icon/spinner')['default']
  const IconWindsock: typeof import('~icons/icon/windsock')['default']
}
